server:
  port: 12006

spring:
  application:
    name: grievance-notification-center-ms
  zipkin:
    base-url: http://localhost:9411/
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
